baseURL = 'http://godotrecipes.com/4.x/'
languageCode = 'en-us'
publishDir = "../docs/4.x"
title = 'Godot 4 Recipes'
theme = "hugo-theme-relearn"
pygmentsStyle = "dracula"
pygmentsCodeFences = true
staticDir = ["static", "../static_shared"]
themesDir = "../themes_shared"

[params]
    disableNextPrev = true
    themeVariant = "green"
    disableInlineCopyToClipBoard = true
    godotVer = "4.X"
    godotVerToggle = "3.X"

[outputs]
    home = [ "HTML", "RSS", "JSON"]

[markup.goldmark.renderer]
    unsafe = true

[minify]
  minifyOutput = true

[[menu.shortcuts]]
name = "<i class='fas fa-tags'></i>&nbsp;Tags"
url = "/tags"
weight = 30
