baseURL = "http://kidscancode.org/godot_recipes/"
publishDir = "../docs"
languageCode = "en-us"
title = "Godot Recipes by KidsCanCode"
theme = "hugo-theme-learn-cb"
pygmentsStyle = "dracula"
pygmentsCodeFences = true
googleAnalytics = "UA-39851424-1"
disqusShortname = "kidscancode"

[params]
    disableNextPrev = true
    themeVariant = "green"
    disableInlineCopyToClipBoard = true

[outputs]
    home = [ "HTML", "RSS", "JSON"]

[minify]
  disableCSS = false
  disableHTML = false
  disableJS = false
  disableJSON = false
  disableSVG = false
  disableXML = false
  minifyOutput = false
  [minify.tdewolff]
    [minify.tdewolff.css]
      decimals = -1
      keepCSS2 = true
    [minify.tdewolff.html]
      keepConditionalComments = true
      keepDefaultAttrVals = true
      keepDocumentTags = true
      keepEndTags = true
      keepWhitespace = false
    [minify.tdewolff.js]
    [minify.tdewolff.json]
    [minify.tdewolff.svg]
      decimals = -1
    [minify.tdewolff.xml]
      keepWhitespace = false