baseURL = "http://kidscancode.org/godot_lessons/"
publishDir = "../docs"
languageCode = "en-us"
title = "Godot Lessons by KidsCanCode"
theme = "hugo-theme-learn-cb"
pygmentsStyle = "vim"
pygmentsCodeFences = true
googleAnalytics = "UA-39851424-1"
disqusShortname = "kidscancode"

[params]
    themeVariant = "green"
    disableInlineCopyToClipBoard = true